export const zrodlaProjektu = [
  {
    src:
      "https://pl.wikipedia.org/wiki/Pomnik_Pokoju_w_Hiroszimie?fbclid=IwAR3QMbuohWllaAqyrEksrsSIXPuQ7C4vsiPqxXrzeK2FxtWTL9qstqzi2UM",
  },
  {
    src:
      "https://pl.wikipedia.org/wiki/Muzeum_Bomby_Atomowej_w_Nagasaki?fbclid=IwAR0-GTrFjYZE7jADK3I6zQrP61-ffyayVqMudlVWIbk-wczqu1O5uh8Ceow",
  },
  {
    src:
      "https://pl.wikipedia.org/wiki/Muzeum_Pokoju_w_Hiroszimie?fbclid=IwAR1SFzWZTZihHUjtkAxf3ExPLPimFlv0Jn8yhlBEPB7V-j_39P1cdlKGCNc",
  },
  {
    src:
      "https://pl.wikipedia.org/wiki/Sadako_Sasaki?fbclid=IwAR3S7Om-QID7C_SK7yplA213HLbvbGmcehp5IGVDLUYOGncvTsXICufMhvA",
  },
  {
    src:
      "https://pl.wikipedia.org/wiki/Pomnik_Pokoju_w_Hiroszimie?fbclid=IwAR2klYW2MPZUcf0ShrVFNjUy1XX7XIaW60YBO4cv3sI6DA-wJhfogW0oKwg",
  },
  {
    src:
      "https://www.gedanopedia.pl/gdansk/?title=POMNIK_%E2%80%9EKWIAT_%C5%BBYCIA_I_POKOJU&fbclid=IwAR3W2Ikhb6BSNizR9q-r4sNPSY7uJDTiIqsgUe56-5hU9XxKUyP6Rg6VOlQ",
  },
  {
    src:
      "https://en.wikipedia.org/wiki/Nagasaki_Peace_Park?fbclid=IwAR3QMbuohWllaAqyrEksrsSIXPuQ7C4vsiPqxXrzeK2FxtWTL9qstqzi2UM",
  },
  {
    src: "https://en.wikipedia.org/wiki/Nagasaki_Peace_Park",
  },
];
